name: Windows Release
 
on: [push, pull_request]
 
jobs:
  build:
    runs-on: windows-2022
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Install Conan
        uses: conan-io/setup-conan@v1
 
      - name: Display Conan information
        run: |
          echo "Installed Conan version: ${{ steps.conan.outputs.conan-version }}"
          echo "Conan home directory: ${{ steps.conan.outputs.conan-home }}"
 
      - name: Setup
        run: ./setup_release.bat
      
      - name: Build project
        run: cmake --build build --config Release --parallel
      
      - name: Run tests
        run: ./build/runtime/Release/P2LibTests.exe
